### ISSUE TITLE
Add at-satellite brightness

### ISSUE THREAD

**Issue by dnomadb** [mapbox/rio-toa#17]
Add conversion to At-Satellite Brightness Temperature as outlined here: http://landsat.usgs.gov/Landsat8_Using_Product.php

cc @virginiayung

**Comment by virginiayung** [comment]
- [x] Python api, cli, tests (97%), and docstrings added in PR https://github.com/mapbox/rio-toa/pull/20.
  Status: [PR merged](https://github.com/mapbox/rio-toa/pull/20)
- [x] README updated in commit [5458e77](https://github.com/mapbox/rio-toa/commit/5458e77327413803e2243e854bcf83db7c028e12)

cc @dnomadb
