### ISSUE TITLE
Polishing rio toa

### ISSUE THREAD

**Issue by celoyd** [mapbox/rio-toa#19]
Via chat, there are various minor loose ends and quirks in `rio toa` that don’t block anything in particular but should be tightened up.

These range from documentation ambiguities to bits of code that could be neatened without design changes. Anything big enough to ticket should be its own ticket.

I’ve started this process in [the `user-friendlier` branch](https://github.com/mapbox/rio-toa/pull/18), with @virginiayung and @dnomadb watching and contributing as appropes.

**Comment by virginiayung** [comment]
### Contributing to [user-friendlier branch](https://github.com/mapbox/rio-toa/pull/18):

#### Changes made to functionality:
1. Click optional parameter **`--dst-dtype`**: Took out `float32`, `float64` and set the default as **`uint16`** for [radiance cli](https://github.com/mapbox/rio-toa/pull/18/commits/e97a8ff565517225c615e5af960b15b24f2cbdd9#diff-d526d88077ac04268b1226915c1fecffL27) and [reflectance cli](https://github.com/mapbox/rio-toa/pull/18/commits/e97a8ff565517225c615e5af960b15b24f2cbdd9#diff-d526d88077ac04268b1226915c1fecffL63).

#### Tests Added:
1. [test_rescale_dtype_error](https://github.com/mapbox/rio-toa/pull/18/commits/e97a8ff565517225c615e5af960b15b24f2cbdd9#diff-21ded7212d9b10a783afdbb2755775d3R100)
2. [test uint8 output](https://github.com/mapbox/rio-toa/pull/18/commits/72f34745c9e0a4a41b703e51ba209a1248d26002#diff-1da5d99b695c5726c59c987ad61b3f16R95)

#### Pep8
1. All files in tests: [commit 72f34](https://github.com/mapbox/rio-toa/blob/72f34745c9e0a4a41b703e51ba209a1248d26002/)
2. All files in rio_toa: [commit e97a8](https://github.com/mapbox/rio-toa/blob/e97a8ff565517225c615e5af960b15b24f2cbdd9/rio_toa/reflectance.py)

**Comment by virginiayung** [comment]
We can come back to do more polishing at some point. 
**Status: [PR Merged](https://github.com/mapbox/rio-toa/pull/18)**
Closing ticket for now 🎉 

cc @celoyd @dnomadb
