### ISSUE TITLE
Multiple band inputs

### ISSUE THREAD

**Issue by dnomadb** [mapbox/rio-toa#8]
We can integrate the stacking step as part of this command - basically, take `n` inputs and output an `n` band raster.
# Questions
- How do we handle band numbers? Do we make a band / filename template mandatory w/ multiple bands (w/ the default being the default naming)?

cc @virginiayung @celoyd @perrygeo

**Comment by virginiayung** [comment]
#### Current settings for reflectance: PR: https://github.com/mapbox/rio-toa/pull/13:
- ##### Default: Take any number of bands (single or multiple), stack them and output a single **n** band tif

cc @dnomadb @celoyd @perrygeo

**Comment by virginiayung** [comment]
Merged and 🚢 : https://github.com/mapbox/rio-toa/pull/13#issuecomment-233762751
