### ISSUE TITLE
Optional user-provided filename band # template

### ISSUE THREAD

**Issue by dnomadb** [mapbox/rio-toa#9]
We'll have to handle filename parsing as-is, so it is trivial to add this as an option w/ a default of `LC8.*\_B{b}.TIF`, w/ `{b}` as the to-be-extracted band.

cc @virginiayung @perrygeo @celoyd

**Comment by dnomadb** [comment]
@virginiayung some prior art:
CLI:
https://github.com/mapbox/untiler/blob/master/untiler/scripts/cli.py#L25
Code:

``` python
fnames = ['tests/LC80100202015018LGN00_B1.TIF', 'tests/LC80100202015018LGN00_B2.TIF', 'tests/LC80100202015018LGN00_B3.TIF']
template = 'tests\/LC8.*\_B{b}.TIF'

matcher = template.replace('{b}', '([1-9]+)')
matcher = re.compile(matcher)

bands = [int(matcher.findall(f)[0]) for f in fnames if matcher.match(f)]
```

**Comment by virginiayung** [comment]
🚢 https://github.com/mapbox/rio-toa/pull/11
